services:
  - type: web
    name: finance-manager
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn finance_manager.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: finance_manager.settings
      - key: PYTHON_VERSION
        value: 3.11
